# Generated by Django 3.1.2 on 2020-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201105_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
