# Generated by Django 3.1.2 on 2020-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=250)),
                ('auther', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
