# Generated by Django 3.1.2 on 2020-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articls_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
